# Generated by Django 4.2.5 on 2023-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(default='', max_length=100, verbose_name='last Name')),
                ('mobileNumber', models.CharField(default='', max_length=30, verbose_name='Mobile Number')),
                ('tc', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestApi',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('mobileNumber', models.CharField(default='', max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('added_data', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
